"""The bounded fix loop, on its offline path (no model, no network).

Covers the properties that make it safe to point at a real file: it strips the
provenance and the character tells in one go, it converges and then does nothing
on a second run (idempotent), it never exceeds its pass budget, and --rename is
honoured only when asked.
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from reweave.fix import run_fix  # noqa: E402
from reweave.scrub.metadata_scrubber import FileMetadataScrubber  # noqa: E402

_XATTR = "/usr/bin/xattr" if sys.platform == "darwin" else None


def _seed_wherefrom(path: Path, url: str) -> bool:
    import plistlib

    blob = plistlib.dumps([url], fmt=plistlib.FMT_BINARY)
    if hasattr(os, "setxattr"):
        os.setxattr(str(path), "com.apple.metadata:kMDItemWhereFroms", blob)
        return True
    if _XATTR:
        subprocess.run([_XATTR, "-wx", "com.apple.metadata:kMDItemWhereFroms",
                        blob.hex(), str(path)], check=True)
        return True
    return False


# Em dash and a curly apostrophe are unicode tells; the frontmatter and the
# HTML-ish line are provenance. One file, every offline layer at once.
_DIRTY = (
    "---\ntitle: Real Title\ngenerator: ChatGPT\n---\n\n"
    "<!-- Generated by ChatGPT -->\n\n"
    "The revenue rose 40% in Q3—a big jump. It’s the best we’ve seen.\n"
)


def _tmp(name: str, body: str) -> Path:
    d = Path(tempfile.mkdtemp())
    f = d / name
    f.write_text(body, encoding="utf-8")
    return f


def test_fix_strips_metadata_and_scrubs_unicode_offline():
    f = _tmp("notes.md", _DIRTY)
    seeded = _seed_wherefrom(f, "https://chatgpt.com/c/abc-123")

    res = run_fix(str(f))  # regenerate defaults to False: offline

    assert res.converged
    assert len(res.passes) <= 3
    text = Path(res.path).read_text(encoding="utf-8")
    assert "—" not in text and "’" not in text, "unicode tells survived"
    assert "generator: ChatGPT" not in text and "Generated by ChatGPT" not in text
    assert "Real Title" in text and "40%" in text, "real content must survive"
    if seeded:
        left = {f.key for f in FileMetadataScrubber().inspect(res.path).findings}
        assert "com.apple.metadata:kMDItemWhereFroms" not in left


def test_fix_is_idempotent():
    f = _tmp("notes.md", _DIRTY)
    _seed_wherefrom(f, "https://chatgpt.com/c/abc-123")
    first = run_fix(str(f))
    second = run_fix(str(first.path))
    assert second.converged
    assert all(not p.changed for p in second.passes), "a clean file was changed again"


def test_fix_respects_pass_budget():
    f = _tmp("notes.md", _DIRTY)
    res = run_fix(str(f), max_passes=1)
    assert len(res.passes) == 1


def test_fix_rename_only_when_asked():
    f = _tmp("ChatGPT-Quarterly Notes.md", "A plain sentence. And another one.\n")
    kept = run_fix(str(f))  # no rename
    assert Path(kept.path).name == "ChatGPT-Quarterly Notes.md"

    f2 = _tmp("ChatGPT-Quarterly Notes.md", "A plain sentence. And another one.\n")
    renamed = run_fix(str(f2), rename=True)
    assert Path(renamed.path).name == "Quarterly Notes.md"
    assert renamed.converged


def test_fix_offline_never_reports_regenerate():
    f = _tmp("notes.md", _DIRTY)
    res = run_fix(str(f))
    assert res.regenerate is False
    assert all(not p.regenerated for p in res.passes)
