"""Stage 0: provenance that survives a perfect rewrite.

Uses the real downloaded fixtures in `tests/` where they are present. Those files
came from actual ChatGPT and Gemini downloads and carry genuine extended
attributes, which is worth far more than anything synthetic: the Gemini URL alone
embeds a unique per-response identifier, and no invented example would have
predicted that.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from reweave.scrub import FileMetadataScrubber  # noqa: E402

_XATTR = "/usr/bin/xattr" if sys.platform == "darwin" else shutil.which("xattr")


def _seed_wherefroms(path: Path, url: str) -> bool:
    """Write the attribute macOS writes on download. Returns False if unsupported."""
    import plistlib

    blob = plistlib.dumps([url], fmt=plistlib.FMT_BINARY)
    if hasattr(os, "setxattr"):
        os.setxattr(str(path), "com.apple.metadata:kMDItemWhereFroms", blob)
        return True
    if _XATTR:
        subprocess.run([_XATTR, "-wx", "com.apple.metadata:kMDItemWhereFroms",
                        blob.hex(), str(path)], check=True)
        return True
    return False


def test_finds_and_removes_chat_provenance(tmp_path=None):
    tmp = Path(tmp_path) if tmp_path else Path(
        __import__("tempfile").mkdtemp())
    f = tmp / "notes.md"
    f.write_text(
        "---\ntitle: Real Title\ngenerator: ChatGPT\nmodel: gpt-5\n---\n\n"
        "<!-- Generated by ChatGPT -->\n\nThe revenue rose 40% in Q3.\n",
        encoding="utf-8",
    )
    seeded = _seed_wherefroms(f, "https://chatgpt.com/c/abc-123")

    s = FileMetadataScrubber()
    found = s.inspect(str(f))
    kinds = {x.layer for x in found.findings}
    assert "frontmatter" in kinds and "inline" in kinds
    if seeded:
        assert "xattr" in kinds, "the source URL was not detected"

    report = s.scrub_file(str(f))
    text = f.read_text(encoding="utf-8")

    assert "ChatGPT" not in text and "gpt-5" not in text
    assert "Real Title" in text, "real front-matter content must survive"
    assert "40%" in text, "the prose itself must be untouched"
    assert report.removed

    # Whatever it claims to have removed must actually be gone.
    still = {(x.layer, x.key) for x in s.inspect(str(f)).findings}
    for x in report.removed:
        assert (x.layer, x.key) not in still, f"claimed removal of {x.key}, still present"


def test_filename_is_treated_as_provenance():
    """`ChatGPT-Victoria Memorial Essay.md` names its source in the one place
    everyone sees first. Found because a real download arrived that way. The
    non-Western labs (Kimi, Qwen, DeepSeek) tag downloads the same way, so the
    detector has to know their names too, not just the six Western vendors."""
    s = FileMetadataScrubber()
    tmp = Path(__import__("tempfile").mkdtemp())
    for name, expected in (
        ("ChatGPT-Quarterly Notes.md", "Quarterly Notes.md"),
        ("Kimi-Quarterly Notes.md", "Quarterly Notes.md"),
        ("Qwen-Quarterly Notes.md", "Quarterly Notes.md"),
        ("Deepseek-Quarterly Notes.md", "Quarterly Notes.md"),
    ):
        f = tmp / name
        f.write_text("Nothing incriminating in the prose at all.\n", encoding="utf-8")
        report = s.inspect(str(f))
        assert any(x.layer == "filename" for x in report.findings), name
        assert s.suggested_name(str(f)) == expected, name

    f = tmp / "ChatGPT-Quarterly Notes.md"

    # Renaming changes the caller's path, so it must never happen implicitly.
    FileMetadataScrubber().scrub_file(str(f))
    assert f.exists(), "file was renamed without --rename"

    renamer = FileMetadataScrubber(rename=True)
    renamer.scrub_file(str(f))
    assert not f.exists() and (tmp / "Quarterly Notes.md").exists()


def test_clean_file_reports_clean():
    tmp = Path(__import__("tempfile").mkdtemp())
    f = tmp / "notes.md"
    f.write_text("A plain sentence with no provenance anywhere.\n", encoding="utf-8")
    report = FileMetadataScrubber().inspect(str(f))
    assert report.clean, [str(x) for x in report.findings]


#: Which host each vendor's download actually points at. Data-driven so adding a
#: seventh vendor is a one-line change, not a new `or` branch. Verified against
#: the real `kMDItemWhereFroms` values on the downloaded fixtures.
_EXPECTED_HOST = {
    "chatgpt": ("chatgpt", "openai"),
    "gemini": ("gemini", "google"),
    "grok": ("grok", "x.ai", "x.com"),
    "deepseek": ("deepseek",),
    "kimi": ("kimi", "volces", "moonshot"),
    "qwen": ("qwen", "aliyun", "tongyi"),
}


def test_real_fixtures_carry_source_urls():
    """The whole point, on genuine files rather than ones we constructed.

    git does not preserve extended attributes, so a bare clone has none and
    per-file checks are skipped there. On the machine where these were actually
    downloaded, every fixture's where-from must name its own vendor's host.
    """
    fixtures = sorted(ROOT.glob("tests/*Victoria Memorial*.md"))
    if not fixtures:
        return  # fixtures not present in this checkout

    s = FileMetadataScrubber()
    for path in fixtures:
        report = s.inspect(str(path))
        urls = [x.value.lower() for x in report.findings
                if x.key.endswith("kMDItemWhereFroms")]
        if not urls:
            continue  # xattrs stripped by git; nothing to check on this copy
        vendor = path.name.split("-", 1)[0].lower()
        expected = _EXPECTED_HOST.get(vendor, (vendor,))
        assert any(any(e in u for e in expected) for u in urls), (path.name, urls)
        # And the prose alone gives none of this away.
        assert vendor not in path.read_text(encoding="utf-8").lower()


def test_signed_url_provenance_parts_are_extracted():
    """A signed storage URL leaks a credential, not just a domain. The Kimi
    download carried a ByteDance TOS pre-signed URL; the report must point at the
    embedded access key and signature, or it undersells the exposure."""
    s = FileMetadataScrubber()
    kimi = ROOT / "tests" / "Kimi-Victoria Memorial Essay.md"
    if not kimi.exists():
        return
    report = s.inspect(str(kimi))
    xattr = [f for f in report.findings if f.key.endswith("kMDItemWhereFroms")]
    if not xattr or "volces" not in xattr[0].value.lower():
        return  # bare clone (no xattrs) or a non-signed copy
    labels = {label.split(" ", 1)[0] for label, _ in xattr[0].highlights}
    assert "credential" in labels, xattr[0].highlights
    assert "signature" in labels, xattr[0].highlights
    assert "file-id" in labels, xattr[0].highlights
