"""Stage ⓪ - provenance that survives every word you rewrite.

The blind spot this closes: regeneration replaces the entire token sequence, so
no statistical watermark survives it. But a file is not only its text. Save a
markdown answer from a chat UI and the operating system records where it came
from, in a place no editor shows and no rewrite touches. Verified on a real
download during development:

    com.apple.metadata:kMDItemWhereFroms -> https://www.nature.com/articles/...
    com.apple.quarantine                 -> 0083;6a7aef14;Preview;

Rewrite every sentence in that file and both attributes are still there, still
naming the source. So this pass runs on the PATH, before the text pipeline.

Four layers, each independently checked:

  xattr        macOS/Linux extended attributes. `kMDItemWhereFroms` (source URL),
               `com.apple.quarantine` (downloading app + timestamp), and the
               newer `com.apple.provenance`.
  frontmatter  YAML front matter keys that name a generator or author.
  inline       "Generated by ..." lines and HTML generator comments that tools
               append to exported markdown.
  docx / pdf   Container metadata. DOCX is a zip holding docProps/core.xml
               (dc:creator, cp:lastModifiedBy) and docProps/app.xml
               (Application). PDF keeps an Info dictionary (/Producer,
               /Creator, /Author) and often an XMP packet.

Honest boundary, stated because it matters: for DOCX we rewrite the zip and
genuinely remove the fields. For PDF we REPORT and refuse to claim removal - a
correct rewrite means rebuilding the xref table, and a half-edited PDF that
still carries an XMP packet while reporting "cleaned" would be worse than no
tool at all (Invariant I5). Use a dedicated PDF library for those.

Zero dependencies: `os.*xattr` and `zipfile` are stdlib.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.parse
import zipfile

from ..core.interfaces import MetadataScrubber
from ..core.registry import KIND_METADATA, register
from ..core.types import MetadataFinding, MetadataReport


class XattrUnsupported(RuntimeError):
    """No way to read extended attributes on this platform.

    Raised rather than swallowed, because the alternative is reporting a clean
    bill of health for a file we never actually checked (Invariant I5).
    """

#: Extended attributes that carry provenance. Names are exact; matching is also
#: done by prefix for the `com.apple.metadata:` family.
_PROVENANCE_XATTRS = (
    "com.apple.metadata:kMDItemWhereFroms",   # the source URL - the big one
    "com.apple.metadata:kMDItemDownloadedDate",
    "com.apple.metadata:kMDItemCreator",
    "com.apple.metadata:kMDItemAuthors",
    "com.apple.quarantine",                   # downloading app + timestamp
    "user.xdg.origin.url",                    # Linux/GNOME equivalent
    "user.xdg.referrer.url",
)

#: Deliberately NOT flagged. `com.apple.provenance` appears on files created
#: locally that were never downloaded (verified: `echo hello > new.txt` has it),
#: it carries no source URL, and macOS re-creates it on write. Reporting it made
#: every single run end with a "1 trace NOT removable" warning, including for
#: files with nothing wrong. A warning that always fires teaches people to
#: ignore warnings, which costs more than the trace it was reporting.
_IGNORED_XATTRS = frozenset({
    "com.apple.provenance",
    "com.apple.lastuseddate#PS",   # when it was opened, not where it came from
    "com.apple.macl",              # per-app access control, not provenance
})

#: Front-matter keys whose value names the tool or account that produced the file.
_FRONTMATTER_KEYS = frozenset({
    "generator", "generated_by", "generatedby", "created_with", "createdwith",
    "author", "creator", "producer", "source", "source_url", "model", "tool",
    "assistant", "ai", "ai_model", "exported_from", "chatgpt", "openai",
})

_FRONTMATTER = re.compile(r"\A---\r?\n(.*?)\r?\n---\r?\n", re.S)
_FM_LINE = re.compile(r"^([A-Za-z_][\w-]*)\s*:\s*(.+?)\s*$")

#: The vendor alternation, kept in one place so the filename regex, the inline
#: "generated by" line, and the "shared from" footer all recognise the same set.
#: Grew from six Western vendors to include the Chinese labs (Kimi/Moonshot,
#: Qwen, GLM/Zhipu, Doubao, DeepSeek, Ernie) after real Kimi and Qwen downloads
#: arrived carrying provenance the original list would have missed.
_VENDOR_ALT = (
    r"chatgpt|openai|gpt-?[45o]?\w*|claude|anthropic|gemini|bard|grok|xai|"
    r"copilot|perplexity|deepseek|kimi|moonshot|qwen|tongyi|glm|zhipu|doubao|"
    r"ernie|llama|mistral|mixtral|midjourney|dall-?e"
)

#: Attribution that export tools append to the prose itself.
_INLINE_PATTERNS = (
    re.compile(r"<!--\s*(?:generated|created|exported)\b[^>]*-->", re.I),
    re.compile(r"<meta[^>]+name=[\"']generator[\"'][^>]*>", re.I),
    re.compile(r"^\s*(?:>\s*)?\*{0,2}(?:generated|created|exported|written)\s+(?:by|with|using)\s+"
               r"(?:" + _VENDOR_ALT + r"|ai)\b.*$",
               re.I | re.M),
    re.compile(r"^\s*-{2,}\s*\r?\n\s*\*?(?:shared|exported)\s+(?:from|via)\s+"
               r"(?:" + _VENDOR_ALT + r")\b.*$", re.I | re.M),
)

_TEXT_SUFFIXES = {".md", ".markdown", ".txt", ".mdx", ".rst", ".html", ".htm"}

#: Vendor names that chat UIs put in the download filename. Found the obvious
#: way: a real ChatGPT download used for testing arrived as
#: "ChatGPT-Victoria Memorial Essay.md". Every extended attribute can be stripped
#: and every sentence rewritten, and the file still announces its origin in the
#: one place that gets read first and shared most, its own name.
_AI_NAME = re.compile(
    r"(?:^|[\s_\-\[(])"
    r"(" + _VENDOR_ALT + r")"
    r"(?:$|[\s_\-\])])",
    re.I,
)


# CPython's os.getxattr/listxattr/removexattr are documented "Availability:
# Linux" and genuinely DO NOT EXIST on macOS - which is the one platform where
# kMDItemWhereFroms matters most. Discovered the hard way: the first version of
# this module caught the AttributeError and returned "no metadata found" for a
# file that demonstrably carried a chatgpt.com source URL. A scrubber that
# reports clean without looking is worse than no scrubber.
#
# So macOS goes through /usr/bin/xattr, and any platform with neither path
# raises instead of pretending.
_HAS_OS_XATTR = hasattr(os, "listxattr")
_XATTR_BIN = "/usr/bin/xattr" if sys.platform == "darwin" else shutil.which("xattr")


def _run_xattr(args: list[str]) -> str:
    proc = subprocess.run([_XATTR_BIN, *args], capture_output=True, text=True, timeout=30)
    return proc.stdout


def _xattr_list(path: str) -> list[str]:
    if _HAS_OS_XATTR:
        return list(os.listxattr(path, follow_symlinks=False))  # type: ignore[attr-defined]
    if _XATTR_BIN:
        return [ln.strip() for ln in _run_xattr([path]).splitlines() if ln.strip()]
    raise XattrUnsupported(
        f"cannot read extended attributes on {sys.platform!r}: no os.listxattr "
        "and no xattr binary. File-level provenance is NOT being checked."
    )


def _xattr_get(path: str, name: str) -> bytes:
    if _HAS_OS_XATTR:
        try:
            return os.getxattr(path, name, follow_symlinks=False)  # type: ignore[attr-defined]
        except OSError:
            return b""
    # -px prints the value hex-encoded, which survives the binary plist that
    # kMDItemWhereFroms actually is.
    hexed = "".join(_run_xattr(["-px", name, path]).split())
    try:
        return bytes.fromhex(hexed)
    except ValueError:
        return b""


def _xattr_remove(path: str, name: str) -> bool:
    if _HAS_OS_XATTR:
        try:
            os.removexattr(path, name, follow_symlinks=False)  # type: ignore[attr-defined]
            return True
        except OSError:
            return False
    if not _XATTR_BIN:
        return False
    proc = subprocess.run([_XATTR_BIN, "-d", name, path],
                          capture_output=True, text=True, timeout=30)
    return proc.returncode == 0


def _xattr_value(path: str, name: str) -> str:
    raw = _xattr_get(path, name)
    if not raw:
        return ""
    # kMDItemWhereFroms is a binary plist. Parsing it properly is the difference
    # between showing the user "<231 bytes>" and showing them the actual URL
    # their file is carrying.
    if raw[:8] == b"bplist00":
        try:
            import plistlib
            val = plistlib.loads(raw)
            if isinstance(val, list):
                return " | ".join(str(v) for v in val if v)
            return str(val)
        except Exception:  # noqa: BLE001 - fall through to the text heuristic
            pass
    text = raw.decode("utf-8", "replace")
    urls = re.findall(r"https?://[^\s\x00-\x1f\"']+", text)
    if urls:
        return " | ".join(urls)
    return "".join(ch for ch in text if ch.isprintable()).strip() or f"<{len(raw)} bytes>"


# A "where from" URL is often more than a homepage. The Kimi download used in
# testing carried a ByteDance Volcano Engine (TOS) pre-signed URL: an embedded
# access-key credential, a per-file UUID, an expiry, and a signature, i.e. a
# live-ish link into the vendor's object storage keyed to an account. Saying "a
# URL is here" undersells that. These break the URL into the parts that actually
# identify you, so a dry run can point at the credential rather than the domain.
_UUID = re.compile(
    r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
)
_QS_CREDENTIAL = re.compile(r"cred|access|secret|(?:^|[-_])key|apikey", re.I)
_QS_SIGNATURE = re.compile(r"sig|signature", re.I)
_QS_EXPIRY = re.compile(r"expir|ttl|\bdate\b", re.I)
_QS_TOKEN = re.compile(r"token|auth|nonce", re.I)


def _short(value: str, limit: int = 32) -> str:
    value = urllib.parse.unquote(value)
    return value if len(value) <= limit else value[:limit] + "..."


def _url_provenance_parts(url: str) -> list[tuple[str, str]]:
    """Decompose a source URL into the components that identify the user.

    Empty for a plain homepage like ``https://chat.qwen.ai/`` (nothing in it
    fingerprints anyone); rich for a signed storage URL. Order is stable so the
    report reads the same way every run.
    """
    parts: list[tuple[str, str]] = []
    try:
        u = urllib.parse.urlsplit(url)
    except ValueError:
        return parts

    for m in _UUID.finditer(u.path):
        parts.append(("file-id", m.group(0)))

    for key, val in urllib.parse.parse_qsl(u.query, keep_blank_values=True):
        if not val:
            continue
        if _QS_CREDENTIAL.search(key):
            parts.append((f"credential ({key})", _short(val)))
        elif _QS_SIGNATURE.search(key):
            parts.append((f"signature ({key})", _short(val)))
        elif _QS_EXPIRY.search(key):
            parts.append((f"expiry ({key})", _short(val, 24)))
        elif _QS_TOKEN.search(key) or (len(val) >= 24 and "/" not in val):
            parts.append((f"token ({key})", _short(val)))
    return parts


def _highlights_for_value(value: str) -> tuple[tuple[str, str], ...]:
    """Identifying components across every URL in a (possibly multi-URL) value."""
    out: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for url in re.findall(r"https?://[^\s|]+", value):
        for part in _url_provenance_parts(url):
            if part not in seen:
                seen.add(part)
                out.append(part)
    return tuple(out)


@register(KIND_METADATA, "file")
class FileMetadataScrubber(MetadataScrubber):
    """Strip provenance from the file around the text."""

    name = "file"

    def __init__(self, strip_frontmatter_keys: bool = True,
                 rename: bool = False) -> None:
        #: When False, front matter is reported but left alone (some pipelines
        #: depend on it for real content).
        self.strip_frontmatter_keys = strip_frontmatter_keys
        #: Renaming changes the path the caller handed us, so it is opt-in.
        self.rename = rename
        #: Set by scrub_file when a rename happens, so callers can follow the file.
        self.renamed_to: str | None = None

    # ---- inspection -------------------------------------------------------

    def _find_xattrs(self, path: str) -> list[MetadataFinding]:
        try:
            names = _xattr_list(path)
        except OSError:
            return []
        # XattrUnsupported deliberately NOT caught: the caller must learn that
        # this layer was not inspected rather than read silence as "clean".
        out = []
        for n in names:
            if n in _IGNORED_XATTRS:
                continue
            if n in _PROVENANCE_XATTRS or n.startswith("com.apple.metadata:kMDItem"):
                val = _xattr_value(path, n)
                out.append(MetadataFinding("xattr", n, val,
                                           highlights=_highlights_for_value(val)))
        return out

    def _find_in_text(self, text: str) -> list[MetadataFinding]:
        out: list[MetadataFinding] = []
        m = _FRONTMATTER.match(text)
        if m:
            # The block opens with '---' on line 1, so the first key line is 2.
            for idx, line in enumerate(m.group(1).splitlines()):
                fm = _FM_LINE.match(line)
                if fm and fm.group(1).lower() in _FRONTMATTER_KEYS:
                    out.append(MetadataFinding("frontmatter", fm.group(1), fm.group(2),
                                               line=idx + 2))
        for pat in _INLINE_PATTERNS:
            for hit in pat.finditer(text):
                start = hit.start()
                out.append(MetadataFinding(
                    "inline", "attribution", hit.group(0).strip(),
                    line=text.count("\n", 0, start) + 1, span=(start, hit.end()),
                ))
        return out

    def _find_docx(self, path: str) -> list[MetadataFinding]:
        out: list[MetadataFinding] = []
        try:
            with zipfile.ZipFile(path) as z:
                for part in ("docProps/core.xml", "docProps/app.xml"):
                    if part not in z.namelist():
                        continue
                    xml = z.read(part).decode("utf-8", "replace")
                    for tag in ("dc:creator", "cp:lastModifiedBy", "Application",
                                "dc:title", "cp:keywords", "Company"):
                        for hit in re.finditer(rf"<{tag}>(.*?)</{tag}>", xml, re.S):
                            if hit.group(1).strip():
                                out.append(MetadataFinding("docx", tag, hit.group(1).strip()))
        except (zipfile.BadZipFile, OSError):
            pass
        return out

    def _find_pdf(self, path: str) -> list[MetadataFinding]:
        out: list[MetadataFinding] = []
        try:
            with open(path, "rb") as fh:
                blob = fh.read()
        except OSError:
            return out
        for field in (b"Producer", b"Creator", b"Author", b"Title"):
            for hit in re.finditer(rb"/" + field + rb"\s*\((.{0,200}?)\)", blob, re.S):
                val = hit.group(1).decode("latin-1", "replace").strip()
                if val:
                    # removable=False is the honest part: we can SEE it, we do
                    # not rewrite PDF xref tables, so we will not claim removal.
                    out.append(MetadataFinding("pdf", field.decode(), val, removable=False))
        if b"<x:xmpmeta" in blob:
            out.append(MetadataFinding("pdf", "XMP packet",
                                       "embedded XMP metadata present", removable=False))
        return out

    def suggested_name(self, path: str) -> str:
        """The filename with the vendor tag taken out, separators tidied."""
        stem, suffix = os.path.splitext(os.path.basename(path))
        cleaned = _AI_NAME.sub(" ", stem)
        cleaned = re.sub(r"[\s_-]{2,}", " ", cleaned).strip(" _-")
        return (cleaned or "document") + suffix

    def inspect(self, path: str) -> MetadataReport:
        findings = list(self._find_xattrs(path))
        suffix = os.path.splitext(path)[1].lower()

        base = os.path.basename(path)
        if _AI_NAME.search(os.path.splitext(base)[0]):
            # removable, but only via rename, which changes the caller's path.
            # Never done implicitly: silently moving someone's file is worse
            # than leaving a trace they were told about.
            findings.append(MetadataFinding("filename", "name", base))

        if suffix in _TEXT_SUFFIXES:
            try:
                with open(path, "r", encoding="utf-8", errors="replace") as fh:
                    findings += self._find_in_text(fh.read())
            except OSError:
                pass
        elif suffix in {".docx", ".pptx", ".xlsx"}:
            findings += self._find_docx(path)
        elif suffix == ".pdf":
            findings += self._find_pdf(path)

        return MetadataReport(path=path, findings=tuple(findings))

    # ---- removal ----------------------------------------------------------

    def scrub_file(self, path: str) -> MetadataReport:
        """Remove what can be removed, then RE-INSPECT and report what survived.

        The verification pass is not belt-and-braces, it is load-bearing. Two
        things were caught by it during development:

        1. Writing the file re-creates attributes. Rewriting the text after
           stripping xattrs made macOS re-add `com.apple.provenance`, so the
           original order reported a removal that had already been undone. Text
           is now rewritten FIRST, and xattrs stripped after.
        2. Some attributes are system-managed and come back regardless.

        A removal tool that trusts its own delete calls will confidently tell
        users a file is clean when it is not. So we ask the file again.
        """
        report = self.inspect(path)

        # Content first: writing the file can re-create filesystem attributes.
        attempted: list[MetadataFinding] = []
        text_findings = [f for f in report.findings if f.layer in ("frontmatter", "inline")]
        if text_findings:
            attempted += self._rewrite_text(path, text_findings)

        docx_findings = [f for f in report.findings if f.layer == "docx"]
        if docx_findings:
            attempted += self._rewrite_docx(path, docx_findings)

        for f in report.findings:
            if f.layer == "xattr" and _xattr_remove(path, f.key):
                attempted.append(f)

        # Rename last: everything above addresses `path`, so moving it earlier
        # would leave the other passes operating on a file that no longer exists.
        self.renamed_to = None
        name_findings = [f for f in report.findings if f.layer == "filename"]
        if name_findings and self.rename:
            target = os.path.join(os.path.dirname(path) or ".", self.suggested_name(path))
            if not os.path.exists(target):
                os.rename(path, target)
                self.renamed_to = target
                path = target
                attempted += name_findings

        # Ask the file what actually survived, rather than trusting the deletes.
        still_present = {(f.layer, f.key) for f in self.inspect(path).findings}
        removed = tuple(f for f in attempted if (f.layer, f.key) not in still_present)
        unremovable = tuple(
            f for f in report.findings
            if not f.removable or (f.layer, f.key) in still_present
        )
        return MetadataReport(path=path, findings=report.findings,
                              removed=removed, unremovable=unremovable)

    def _rewrite_text(self, path: str, findings: list[MetadataFinding]) -> list[MetadataFinding]:
        with open(path, "r", encoding="utf-8") as fh:
            text = fh.read()
        original = text

        for pat in _INLINE_PATTERNS:
            text = pat.sub("", text)

        if self.strip_frontmatter_keys:
            m = _FRONTMATTER.match(text)
            if m:
                kept = [ln for ln in m.group(1).splitlines()
                        if not (_FM_LINE.match(ln)
                                and _FM_LINE.match(ln).group(1).lower() in _FRONTMATTER_KEYS)]
                # An empty front-matter block is itself a tell; drop it entirely.
                block = f"---\n{chr(10).join(kept)}\n---\n" if any(k.strip() for k in kept) else ""
                text = block + text[m.end():]

        text = re.sub(r"\n{3,}", "\n\n", text).lstrip("\n")
        if text == original:
            return []
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        return findings

    def _rewrite_docx(self, path: str, findings: list[MetadataFinding]) -> list[MetadataFinding]:
        """Rewrite the zip with the identifying fields emptied.

        Rebuilt into a temp file and moved into place, so an error mid-write
        cannot leave the user with a truncated document.
        """
        blank = ("dc:creator", "cp:lastModifiedBy", "Application", "Company", "cp:keywords")
        try:
            fd, tmp = tempfile.mkstemp(suffix=".docx")
            os.close(fd)
            with zipfile.ZipFile(path) as src, zipfile.ZipFile(
                tmp, "w", zipfile.ZIP_DEFLATED
            ) as dst:
                for item in src.infolist():
                    data = src.read(item.filename)
                    if item.filename in ("docProps/core.xml", "docProps/app.xml"):
                        xml = data.decode("utf-8", "replace")
                        for tag in blank:
                            xml = re.sub(rf"<{tag}>.*?</{tag}>", f"<{tag}></{tag}>", xml, flags=re.S)
                        data = xml.encode("utf-8")
                    dst.writestr(item, data)
            shutil.move(tmp, path)
            return findings
        except (zipfile.BadZipFile, OSError):
            return []
